### ISSUE TITLE
Error 'multiple repeat in regex string'

### ISSUE THREAD

**Issue by spoutn1k** [E4S-Project/e4s-cl#22]
Running with `mvapich2`:

```
quartz2123{user1}51: e4s-cl mpirun -np 4 ./ring
Using selected profile default-4d58938472ef20d7983858a9769c80e3225ba6af4212de66264756adec8dcf6d
Inside container
Inside container
Inside container
Inside container
36567 on quartz2123: An unexpected error exception was raised:

multiple repeat at position 8

Traceback (most recent call last):
  File "/usr/global/tools/tau/training/e4s-cl-July21/bin/e4s-cl", line 17, in <module>
    sys.exit(cli_main_cmd.main(sys.argv[1:]))
  File "/usr/global/tools/tau/training/e4s-cl-July21/bin/../packages/e4s_cl/cli/commands/__main__.py", line 204, in main
    return cli.execute_command([cmd], cmd_args)
  File "/usr/global/tools/tau/training/e4s-cl-July21/bin/../packages/e4s_cl/cli/__init__.py", line 320, in execute_command
    return find_command(cmd).main(cmd_args)
  File "/usr/global/tools/tau/training/e4s-cl-July21/bin/../packages/e4s_cl/cli/commands/__execute.py", line 207, in main
    for line in libset.ldd_format():
  File "/usr/global/tools/tau/training/e4s-cl-July21/bin/../packages/e4s_cl/cf/libraries/libraryset.py", line 360, in ldd_format
    return list(map(line, set.union(self.sonames, self.missing_libraries)))
  File "/usr/global/tools/tau/training/e4s-cl-July21/bin/../packages/e4s_cl/cf/libraries/libraryset.py", line 352, in line
    if lib := self.find(soname):
  File "/usr/global/tools/tau/training/e4s-cl-July21/bin/../packages/e4s_cl/cf/libraries/libraryset.py", line 310, in find
    matches = set(filter(lambda x: re.match(soname, x.soname), self))
  File "/usr/global/tools/tau/training/e4s-cl-July21/bin/../packages/e4s_cl/cf/libraries/libraryset.py", line 310, in <lambda>
    matches = set(filter(lambda x: re.match(soname, x.soname), self))
  File "/usr/global/tools/tau/training/e4s-cl-July21/conda/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/usr/global/tools/tau/training/e4s-cl-July21/conda/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/global/tools/tau/training/e4s-cl-July21/conda/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/global/tools/tau/training/e4s-cl-July21/conda/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/global/tools/tau/training/e4s-cl-July21/conda/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/global/tools/tau/training/e4s-cl-July21/conda/lib/python3.8/sre_parse.py", line 671, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 8

This is a bug in E4S Container Launcher.
Please raise an issue on Github with the contents of '/g/g24/user1/.local/e4s_cl/debug_log’.
```

**Comment by spoutn1k** [comment]
Reopening due to auto-close, wainting for confirmation from user.
